
export const GET_COUNTRIES="GET_COUNTRIES";
export const ADD_TO_CART="ADD_TO_CART";
export const SET_KEYWORD="SET_KEYWORD";
export const SET_FILTERED_DATA="SET_FILTERED_DATA";
export const INCREMENT_VALUE="INCREMENT_VALUE";
